app.js
Temporarily creating duplicates of each JSON file with '_openjdk8' suffixed to the names.
The non-suffixed versions can be removed after changes to the website are proved to work with the suffixed versions.
=> Interim for changeover to named as openjdk8

app.js
Reverts AdoptOpenJDK/openjdk-website-backend#3
This is because we're now likely doing this with separate repositories for future variants such as OpenJDK 9, which makes more sense, because all of the releases and the corresponding JSON files will be in the same place.
=> Revert "Interim for changeover to named as openjdk8"

upload.js
We'd like to set nightly builds deployment per platform
https://github.com/AdoptOpenJDK/openjdk-build/pull/291 .
Current publishRelease API option do not allow same tag( or release) being used again. We'd like each  release can be overidden with same sdk and be appended by different platform sdk as long as those sdk is deployed at same day.
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>
=> Reuse a release to append different platform sdk per same release tag

sbin/Release.sh
Previously VERSION string contained JDK, current VERSION does not, so need to include JDK in the file name when moving files around
Signed-off-by: smlambert <slambert@gmail.com>
=> Fix dropped "JDK" portion of file name

sbin/Release.sh
In Jenkins configuration, VERSION is exported as an environment variable, so will not overwrite it from portion of the artifact name, as it does not suffice.
Note: VERSION also used in gitUpdate.sh as part of the name of the git repo to clone binaries/sha.txt files to.
=> Use env variable VERSION

sbin/Release.sh
Should generate a GitHub release that looks like this:
=> Mark nightly builds as beta

sbin/Release.sh, sbin/releaseCheck.sh
These have been added to the builds, but are not yet released. Note that the counts from the releasecheck.sh tool will be incorrect until I add the signing of .msi and .pkg files
=> Publish GPG signature files

sbin/Release.sh
The current logic in sbin/Release.sh only updates the file name timestamps for jdk|jre archives, and also does not include alpine archives.
This PR ensure any file to publish that contains a timestamp get renamed to the required publish timestamp.
It also corrects the print of the archive type and extends the regex to include all the file types.
eg. Mixture of many different timestamps.. : https://github.com/adoptium/temurin17-binaries/releases/tag/jdk17u-2022-08-12-08-22-beta
Fixes: https://github.com/adoptium/temurin-build/issues/3014
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
=> Ensure release publish script consistently changes all the timestamps

sbin/Release.sh
The newly updated regex needs to allow _fast_startup_ as a variant. Now allows "_" in variant name.
Also, fixed missing echo in the ERROR msg.
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
=> Update publish variant regex to allow underscore for fast_startup artifacts

sbin/releaseCheck.sh
Release tool will not be able to do its checks in the job output without this
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> releaseCheck.sh: use API query and update counts for SBOM .sig file

sbin/Release.sh
The update to the tar ball filename regex did not account for jdk(head) that does not have NN in the OpenJDK-.....tar.gz filename.
=> jdk(head) tar.gz's are named OpenJDK- with no version number

adopt-github-release/src/main/groovy/net/adoptium/release/UploadFiles.groovy
refactor_openjdk_release_tool is currently unable to publish the release notes because there is an additional filter in the UploadFiles.groovy script on top of the one that's in the jenkins job. This fixes that problem.
=> Add release notes filter to UploadFiles.groovy

Jenkinsfile, sbin/Release.sh
Move release job setting and code to git repo
Only upload test results for releases
Fix #111 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Source control release process

Jenkinsfile, sbin/Release.sh
Wrong releaseCheck.sh path
Correct else if  -> elif
Revert to use lowercase jdkversion to work with current jdk pipeline build job
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Correct releaseCheck.sh path and revert jdk version to lowercase

sbin/Release.sh
So jenkins job can correctly show the job status
Fix #116 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Enable -xeo pipeline to correctly return the sh command code

sbin/Release.sh
Ensure Release.sh does not immediately exit if one of the platforms does not have all the artifacts.
Ensure it does not abort if makefailurelogs found.
Fixes: https://github.com/adoptium/github-release-scripts/issues/117
=> Ensure Release.sh does not exit if .sig/json/sha256.txt is not present or being selected

sbin/releaseCheck.sh
Note I've also removed the comments explaining the counts since it duplicates information in the `echo` statement a few lines on that's printed if there is a mismatch and I'd rather they weren't out of sync
=> releaseCheck.sh: Update artefact counts for testimage inclusion

sbin/releaseCheck.sh
Provides a simple fix for https://github.com/adoptium/temurin-build/issues/3064
The job configuration then uses the Advanced shell exit setting: "Exit code to set build unstable"
with a value of "3" to indicate UNSTABLE.
A subsequent feature will update the release job to be a pipeline jenkins file, which can set the result more precisely.
=> Update releaseCheck.sh to exit 3 to indicate UNSTABLE job result

Jenkinsfile, adopt-github-release/src/main/groovy/net/adoptium/release/UploadFiles.groovy
Close #126 
Jenkins new job https://ci.adoptium.net/job/refactor_openjdk_release_tool_new/
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Using credentials for release tool job

sbin/releaseCheck.sh
Removes bash-specific syntax.
Unlike me to make this sort of error as I'm generally quite picky about it :-) The problem didn't show up on my development Fedora system but has an issue on Linux systems using `dash` by default.
Fixes #145 
Also referred to in https://github.com/adoptium/temurin/issues/13#issuecomment-1900826057
=> releaseCheck: fix non-POSIX syntax for Alpine

sbin/Release.sh
As part of enabling beta EA tag driven builds the archive file name regex needs updating to allow timestamp|version field containing "-ea"
ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/902#issue-2105958248
=> Allow for beta EA archive filenames that contain -ea

adopt-github-release/build.gradle, adopt-github-release/gradle/wrapper/gradle-wrapper.properties
Fixes https://github.com/adoptium/github-release-scripts/issues/149
When a large number of artifacts need to be published for a nightly beta build, the heap runs out of space.
Increase max heap setting of gradle app to 2g and upgrade to running under jdk-21
=> Increase release tool java max heap size

sbin/releaseCheck.sh
Currently the code uses a grep on the output that will pick up e.g. `jdk-xx.0.1+y-ea-beta` when searching for `jdk-xx.0.1+y`. This adds `/` around the regex so it will only pick up the entries for the release that it's searching for.
=> releaseCheck: Don't pick up beta builds when checking GA

.github/workflows/test.yml, generate-release-notes/generate-release-notes/test/fetchGitHubCommitsTest.js
bumps the Gradle test CI to Java 21
Also adds Node testing for the generate-release-notes tool
=> bump CI to Java 21 + add Node.js testing

sbin/releaseCheck.sh
We have now [published Linux/riscv64](https://github.com/adoptium/temurin/issues/44) so it should be included in the automated checks.
=> releaseCheck.sh: add linux/riscv64 for JDK17

sbin/Release.sh
The Eclipse Foundation is concerned that the Eclipse Temurin project’s release descriptions on GitHub could be confusing for consumers. Therefore the  Eclipse Foundation directs the  Temurin project to change the GitHub release descriptions from Official Release of jdk-x.x.x to Official Eclipse Temurin Release of jdk-x.x.x for all future releases.
=> change wording for GH releases

sbin/releaseCheck.sh
Now that we release win aarch64 for JDK21+ we should include it in the release check script
=> add support for windows aarch64 to release check

generate-release-notes/generate-release-notes/fetchReleaseNotes.js, generate-release-notes/generate-release-notes/lib/fetchJiraIssues.js
Fixes https://github.com/adoptium/temurin-build/issues/4200
The Jira bug query needs to correctly match the bug database fixVersion used, which for jdk8u is either openjdk8u462 or 8u461
The Jenkins job JDK_VERSION Parameter description has been updated to indicate the required fixVersion values:
```
Upstream JDK Jira Issue fixVersion list (comma separated)
For jdk-11+: In the form MM.0.F. Eg.17.0.1. Note: 18.0.2.1 would be 18.0.2. E.g 20+36 would be 20
For jdk8: Must match openjdkPSU,CPU. eg.openjdk8u462,8u461
EXAMPLES:
21.0.8
openjdk8u462,8u461
```
=> Correct release notes Jira issue fetch
